# Generated by Django 5.0.4 on 2024-05-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='lista',
        ),
        migrations.AlterField(
            model_name='lista',
            name='precio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oferta_lista', to='auctions.oferta'),
        ),
    ]
